import { GoogleGenAI, Modality } from "@google/genai";
import { CameraAngle, UploadedImage } from '../types';

/**
 * Generates an image based on an original image and a camera angle prompt.
 * @param originalImage The user-uploaded image.
 * @param angle The camera angle to apply.
 * @param apiKey The Gemini API key.
 * @returns A base64 encoded string of the generated image.
 */
export const generateImageForAngle = async (
  originalImage: UploadedImage,
  angle: CameraAngle,
  apiKey: string,
): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey });
    const base64ImageData = originalImage.dataUrl.split(',')[1];
    if (!base64ImageData) {
      throw new Error("Invalid data URL for uploaded image.");
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: originalImage.file.type,
            },
          },
          {
            text: angle.promptHint,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    // Check if response has the expected structure
    if (!response || !response.candidates || response.candidates.length === 0) {
      console.error('API Response:', response);
      throw new Error(`API error: ${JSON.stringify(response)}`);
    }

    const candidate = response.candidates[0];
    if (!candidate.content || !candidate.content.parts) {
      console.error('Invalid candidate structure:', candidate);
      throw new Error('API returned invalid response structure');
    }

    for (const part of candidate.content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }

    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error(`Error generating image for angle "${angle.name}":`, error);

    // Check for specific error types
    if (error instanceof Error) {
      if (error.message.includes('API key')) {
        throw new Error('Invalid API key. Please check your Gemini API key.');
      }
      if (error.message.includes('quota') || error.message.includes('limit')) {
        throw new Error('API quota exceeded. Please wait and try again later.');
      }
      if (error.message.includes('model')) {
        throw new Error('Model not available. The gemini-2.5-flash-image model may not be accessible with your API key.');
      }
    }

    throw new Error(`Failed to generate image for "${angle.name}". Check console for details.`);
  }
};

/**
 * Changes the background of a given image based on a text prompt.
 * @param originalImageSrc The base64 data URL of the image to edit.
 * @param mimeType The mime type of the image.
 * @param newBackgroundPrompt The text prompt describing the new background.
 * @param apiKey The Gemini API key.
 * @returns A base64 encoded string of the newly generated image.
 */
export const changeImageBackground = async (
  originalImageSrc: string,
  mimeType: string,
  newBackgroundPrompt: string,
  apiKey: string,
): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey });
    const base64ImageData = originalImageSrc.split(',')[1];
    const prompt = `Change the background of this image to: ${newBackgroundPrompt}. Keep the main subject, style, and camera angle exactly the same. Only change the background.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    if (!response?.candidates?.[0]?.content?.parts) {
      console.error('Background change API Response:', response);
      throw new Error('API returned invalid response');
    }

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    throw new Error("API did not return an image for background change.");
  } catch (error) {
    console.error("Error changing image background:", error);
    throw new Error("Failed to change image background.");
  }
};

/**
 * Upscales an image to a higher quality and resolution.
 * @param imageSrc The base64 data URL of the image to upscale.
 * @param mimeType The mime type of the image.
 * @param apiKey The Gemini API key.
 * @returns A base64 encoded string of the upscaled image.
 */
export const upscaleImage = async (
  imageSrc: string,
  mimeType: string,
  apiKey: string,
): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey });
    const base64ImageData = imageSrc.split(',')[1];
    const prompt = "Upscale this image. Make it sharper, more detailed, and higher quality, while keeping the original content, style, and camera angle perfectly intact.";

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    if (!response?.candidates?.[0]?.content?.parts) {
      console.error('Upscale API Response:', response);
      throw new Error('API returned invalid response');
    }

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    throw new Error("API did not return an upscaled image.");
  } catch (error) {
    console.error("Error upscaling image:", error);
    throw new Error("Failed to upscale image.");
  }
};

/**
 * Removes the background from an image, making it transparent.
 * @param imageSrc The base64 data URL of the image to edit.
 * @param mimeType The mime type of the image.
 * @param apiKey The Gemini API key.
 * @returns A base64 encoded string of the image with a transparent background.
 */
export const removeImageBackground = async (
  imageSrc: string,
  mimeType: string,
  apiKey: string,
): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey });
    const base64ImageData = imageSrc.split(',')[1];
    const prompt = "Perfectly cut out the main subject of this image and make the background transparent. The edges should be clean and precise. Output a PNG image with an alpha channel for transparency.";

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          { text: prompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    if (!response?.candidates?.[0]?.content?.parts) {
      console.error('Remove background API Response:', response);
      throw new Error('API returned invalid response');
    }

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    throw new Error("API did not return an image with background removed.");
  } catch (error) {
    console.error("Error removing image background:", error);
    throw new Error("Failed to remove image background.");
  }
};